### ISSUE TITLE
Large Scan Result List - Doesn't Load Policy Information After Some Number of Results

### ISSUE THREAD

**Issue by CodeUh** [sonatype-nexus-community/vscode-iq-plugin#125]
Can anyone else reproduce this issue? 

If the scan finds over 200 components, it ends up not loading policy information from the IQ server for components further down in the results. When I hover a component that policy information isn't loading for, I see it's missing hash data.

![image](https://user-images.githubusercontent.com/7624295/95606108-7d74c280-0a1f-11eb-84a4-16a2b6f312be.png)
![image](https://user-images.githubusercontent.com/7624295/95606349-d2b0d400-0a1f-11eb-912d-ac3a5454c11d.png)

In this case, I had just created a new Vue2 app using the VueCLI. When doing a full scan of the newly created project with the Nexus IQ CLI, I see it contains 1100 components.

![image](https://user-images.githubusercontent.com/7624295/95606674-481ca480-0a20-11eb-92d1-157c2cf28ebf.png)

**Comment by roger-lau** [comment]
+1
Experienced the exact same scenario here. 

@CodeUh Does it load eventually if you just let it load long enough?

**Comment by CodeUh** [comment]
@roger-lau I tried increasing the extension's setting, Maximum Evaluation Poll Attempts, from 300 to 3000. It doesn't seem to load, even If I wait quite a while. I'll open another instance to do a scan and leave that VS Code instance alone today to see if It come back with results eventually.

**Comment by roger-lau** [comment]
@CodeUh Do you have this error when it loads half way? 
If yes, please increase the limit (screenshot below) in the settings and try again. 
See if that gets the loading moving. 


![5000](https://user-images.githubusercontent.com/22045072/96573455-be62b600-1300-11eb-8cea-d5baf51d4e05.png)
<img width="1196" alt="Screenshot 2020-10-20 at 18 20 07" src="https://user-images.githubusercontent.com/22045072/96573557-e81bdd00-1300-11eb-8052-763399ff3651.png">

**Comment by CodeUh** [comment]
@roger-lau Did this help you get a full scan? It looks like I had already increased it to 50,000 when I checked it this morning. I didn't see the warning on the package-lock.json file. I also tried adding another zero, to 500,000 and am seeing the same issue with the results list not fully loading.

**Comment by hboutemy** [comment]
I don't have this issue on my Mac: can you confirm you're running into this on Windows?

**Comment by CodeUh** [comment]
I can confirm I'm running Windows from the workstation I used VSCode to scan, and also the IQ Server is installed on Windows.

**Comment by CodeUh** [comment]
The results seem to be loading completely now for me. I'm not sure if it's related to the most recent release for the extension 0.7.8 (2020-1020) or something else.

**Comment by hboutemy** [comment]
breaking news: someone else got the same issue, and this time, we found the root cause in IQ logs:
```
2020-12-02 14:44:23,691+0100 ERROR [ApiComponentEvaluationServiceV2-2] *SYSTEM com.sonatype.insight.jaxrs.error.ErrorResponseGenerator - The server base URL (baseUrl) is not configured. More information at https://links.sonatype.com/products/clm/docs/base-url (ID a0ccaf40e8ff4962)
java.lang.IllegalStateException: The server base URL (baseUrl) is not configured. More information at https://links.sonatype.com/products/clm/docs/base-url
	at com.sonatype.insight.brain.service.BaseUrl.getConfigured(BaseUrl.java:76)
	at com.sonatype.insight.brain.service.BaseUrl.get(BaseUrl.java:63)
	at com.sonatype.insight.brain.api.v2.service.ApiSecurityDataAdapter.getSecurityUrl(ApiSecurityDataAdapter.java:74)
	at com.sonatype.insight.brain.api.v2.service.ApiSecurityDataAdapter.convertToDTO(ApiSecurityDataAdapter.java:42)
	at com.sonatype.insight.brain.api.v2.service.ApiComponentDetailsAdapter.convertToDTO(ApiComponentDetailsAdapter.java:78)
	at com.sonatype.insight.brain.api.v2.service.ApiComponentEvaluationServiceV2$ComponentEvaluationTask.run(ApiComponentEvaluationServiceV2.java:234)
	at com.sonatype.insight.brain.security.SystemRunnable.run(SystemRunnable.java:20)
	at com.sonatype.insight.brain.audit.AuditData.lambda$null$1(AuditData.java:93)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

`baseUrl` needs to be configured for APIs to be able to paginate long results!!!

This explains why you had a failure one day, then it disappeared later without knowing why (and why I was not able to reproduce on my local install): you finally configured `baseUrl` because it is useful for other features

**Comment by roger-lau** [comment]
Now I can sleep at night. Hahaha! Thanks @hboutemy !!
