### ISSUE TITLE
Nexus IQ extension: SyntaxError: Unexpected token R in JSON at position 0

### ISSUE THREAD

**Issue by aokegbile** [sonatype-nexus-community/vscode-iq-plugin#22]
Unable to communicate with server. I'm not sure how to debug or triage. 
![image](https://user-images.githubusercontent.com/1121169/64190888-fa0c9900-ce3c-11e9-8a0e-3b162d9b6bdd.png)

![image](https://user-images.githubusercontent.com/1121169/64190940-0b55a580-ce3d-11e9-89b1-b6a5a81bc5d3.png)

**Comment by ctownshend** [comment]
OK, so I can repro this if you dont have IQ running then you will get this error when it tries to access the IQ Server to get the application ID.

See logs below. from IqComponentModel.ts
let response: string = (await this.getApplicationId(
        this.applicationPublicId
      )) as stringÇ;

      let appRep = JSON.parse(response);

SyntaxError: Unexpected token < in JSON at position 0
	at JSON.parse (<anonymous>)
	at IqComponentModel.<anonymous> (/Users/camerontownshend/Documents/Cameron/dev/learnNPM/vscode-plugin/vscode-iq-plugin-jeffry/vscode-iq-plugin/ext-src/IqComponentModel.ts:150:25)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/camerontownshend/Documents/Cameron/dev/learnNPM/vscode-plugin/vscode-iq-plugin-jeffry/vscode-iq-plugin/build/ext-src/IqComponentModel.js:5:58)
	at process._tickCallback (internal/process/next_tick.js:68:7)

response
"<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.17.2</center>
</body>

**Comment by ctownshend** [comment]
Fixed in IqComponentModel.ts, performIqScan

if (response.statusCode != HttpStatus.OK) {            
            reject(`Unable to retrieve Application ID. Could not communicate with server. Server error: ${response.statusCode}`);
            return;
          }
